lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MangoWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MangoWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/categories/:name", CategoryController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", MangoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: MangoWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/mango/application.ex
defmodule Mango.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Mango.Repo,
      # Start the Telemetry supervisor
      MangoWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Mango.PubSub},
      # Start the Endpoint (http/https)
      MangoWeb.Endpoint
      # Start a worker by calling: Mango.Worker.start_link(arg)
      # {Mango.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Mango.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    MangoWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/mango/catalog/catalog.ex
defmodule Mango.Catalog do
  alias Mango.Catalog.Product 

  def list_products do
    product1 = %Product{ name: "Tomato", price: 50, is_seasonal: false,category: "vegetables" }
    product2 = %Product{ name: "Apple", price: 100, is_seasonal: true, category: "fruits" }
    [product1, product2]
  end

  def list_seasonal_products do
    list_products()
    |> Enum.filter(fn(product) -> product.is_seasonal == true end)
  end

   def get_category_products(name) do
    list_products()
    |> Enum.filter(fn(product) -> product.category == name end)
  end
end

lib/mango/catalog/product.ex
defmodule Mango.Catalog.Product do
  defstruct [:name, :price, :is_seasonal, :category] 
end

lib/mango/mailer.ex
defmodule Mango.Mailer do
  use Swoosh.Mailer, otp_app: :mango
end

lib/mango/repo.ex
defmodule Mango.Repo do
  use Ecto.Repo,
    otp_app: :mango,
    adapter: Ecto.Adapters.Postgres
end

lib/mango_web/controllers/category_controller.ex
defmodule MangoWeb.CategoryController do
  use MangoWeb, :controller
  alias Mango.Catalog

  def show(conn, %{"name" => name}) do 
    products = Catalog.get_category_products(name) 
    conn
    |> assign(:products, products)
    |> assign(:name, name) 
    |> render("show.html")
  end

end

lib/mango_web/controllers/page_controller.ex
defmodule MangoWeb.PageController do
  use MangoWeb, :controller
  alias Mango.Catalog


  def index(conn, _params) do
    seasonal_products = Catalog.list_seasonal_products
    conn
    |> assign(:seasonal_products, seasonal_products)
    |> render("index.html")
  end
end

lib/mango_web/views/category_view.ex
defmodule MangoWeb.CategoryView do
  use MangoWeb, :view

  def title_case(name) do
    name
    |> String.downcase
    |> String.capitalize
  end
end

lib/mango_web/views/error_view.ex
defmodule MangoWeb.ErrorView do
  use MangoWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/mango_web/views/layout_view.ex
defmodule MangoWeb.LayoutView do
  use MangoWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/mango_web/views/page_view.ex
defmodule MangoWeb.PageView do
  use MangoWeb, :view
end

lib/mango_web/templates/category/show.html.eex
<div>
  <%= for product <- @products do %>
      <div class="product">
      <h1 class="page-title"><%= title_case @name %></h1>
          <div class="product-name"><%= product.name %></div>
          <div>INR <span class="product-price"><%= product.price %></span></div>
      </div>
  <% end %>
</div>

lib/mango_web/templates/layout/app.html.heex
<main class="container">
 
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/mango_web/templates/layout/live.html.heex
<main class="container">

  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/mango_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Mango", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
       <nav role="navigation">
       <ul>
        <li><%= link "Fuits", to: Routes.category_path(@conn, :show,"fruits") %></li>
        <li><%= link "Vegetables", to: Routes.category_path(@conn, :show,"vegetables") %></li>
       </ul>
        
      </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="mango"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/mango_web/templates/page/index.html.heex
<h1>Seasonal products</h1>
<div>
  <%= for product <- @seasonal_products do %> 
    <div class="product">
      <div class="product-name"><%= product.name %></div>
      <div>INR <span class="product-price"><%= product.price %></span></div>
    </div>
  <% end %>
</div>